feat: add ext packages
vishal-chdhry/kyverno-pkg pull request #4
Opened 2024-03-10 23:19 UTC by eddycharly

Add ext packages.

2024-03-11 08:26 UTC, realshuting requested changes
PR has commented code, what to do with them?

2024-03-11 08:26 UTC, realshuting commented on ext/resource/convert/convert_test.go
Is this no longer valid?

2024-03-11 08:26 UTC, realshuting commented on ext/resource/loader/loader_test.go
Scheduled to be removed?

2024-03-11 10:37 UTC, eddycharly commented on ext/resource/loader/loader_test.go
Nope, to be fixed

2024-03-11 10:37 UTC, eddycharly commented on ext/resource/convert/convert_test.go
Needs fix

2024-04-18 12:07 UTC, realshuting approved these changes

2024-04-18 12:11 UTC, merged